apiVersion: skaffold/v4beta13
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: robsonrc/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .